server:
  port: 8000

spring:
  cloud:
    gateway:
      routes:
        - id: member
          uri: http://127.0.0.1:8001
          # uri: lb://member  # ??????????
          predicates:
            - Path=/member/**

        - id: business
          uri: http://127.0.0.1:8002
          predicates:
            - Path=/business/**

        - id: batch
          uri: http://127.0.0.1:8003
          predicates:
            - Path=/batch/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: '*'
            allowedHeaders: '*'
            allowedMethods: '*'
            allowCredentials: true
            maxAge: 3600