server:
  port: 8000

spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # 如果 Nacos 地址不同，请修改此处
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能
          lower-case-service-id: true
      routes:
        - id: hmdp
          uri: lb://hmdp-service
          predicates:
            - Path=/hmdp/**
          filters:
            - StripPrefix=1 # 去除前缀 /hmdp

        - id: sky-takeout
          uri: lb://sky-takeout-service
          predicates:
            - Path=/sky/**
          filters:
            - StripPrefix=1 # 去除前缀 /sky

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: '*'
            allowedHeaders: '*'
            allowedMethods: '*'
            allowCredentials: true
            maxAge: 3600
